root = "."
tmp_dir = "tmp"
[build]
cmd = "make air-cmd"
bin = "./tmp/main"
delay = 1000                                    # ms
exclude_dir = ["tmp", "vendor", "node_modules"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]
